all: iso lxd-create

iso:
  #!/usr/bin/env bash
  set -euxo pipefail
  cd {{justfile_directory()}}
  nixos-generate --format iso --configuration ./iso.nix -o nix-iso-out
  sudo mv nix-iso-out/iso/nixos-*.iso nix-iso-out/iso/nixos.iso

lxd-create:
  #!/usr/bin/env bash
  set -euxo pipefail
  cd {{justfile_directory()}}/vm
  sudo -E lxc launch nix nix --console=vga --vm < lxc-vm.yml
  # lxc config edit nix

lxd-provision:



view:
  lxc start nix
  # cat 3lxc exec nix --
  sudo -E lxc console --type=vga nix
