---
- name: system
  tags: ['system']
  block:
  - name: create configs
    block:
    - name: ensure config dirs
      file:
        path: "/{{ item.path }}"
        state: directory
      with_filetree: '../templates'
      when: item.state == 'directory'

    - name: copy configs
      template:
        src: '{{ item.src }}'
        dest: '/{{ item.path }}'
        mode: '{{ item.mode }}'
        owner: root
      with_filetree: '../templates'
      when: item.state == 'file'

  - name: symlink resolv.conf stub
    file:
      src: "/run/systemd/resolve/stub-resolv.conf"
      dest: "/etc/resolv.conf"
      state: link

  - name: configure locales
    block:
    - name: generate locales
      locale_gen:
        name: "{{ item }}.UTF-8"
        state: present
      loop: "{{ locales }}"

    - name: set timezone and hardware clock
      timezone:
        name: "{{ timezone }}"
        hwclock: UTC

    - name: check if ntp is active
      command: timedatectl show --value -p NTP
      register: ntp_active
      changed_when: False
    - name: enable time sync
      command: timedatectl set-ntp true
      when: not ntp_active

  - name: add user to groups
    user:
      name: "{{ user.name }}"
      groups: {{ item }}
      append: yes
    with_items:
    - cups
    - libvirt

  - import_tasks: maintenance.yml
