---
- name: maintenance tasks
  tags: maintenance
  block:

  - name: refresh pacman cache and upgrade the system
    tags: maintenance
    pacman: update_cache=yes upgrade=yes

  - name: Clean orphan packages
    command: paru -c --noconfirm
    register: output
    changed_when: output.stdout.find('removing') != -1

  - name: Clean paccache.
    command: paccache -rk1
    register: output
    changed_when: output.stdout.find('packages removed') != -1

  - name: update antibody plugins
    become_user: "{{ user.name }}"
    command: antibody update
    register: output
    changed_when: output.stdout.find('updated') != -1
