- hosts: localhost
  name: bootstrap
  connection: local
  become: true

  collections:
    - debops.debops

  tasks:
    - name: disks
      block:
        - name: boot
          block:
            - name: partition
              parted:
                name: efi
                label: gpt
                device: /dev/sda
                number: 1
                state: present
                flags: [boot]
                part_end: 512MiB

            - name: filesystem
              filesystem:
                dev: /dev/disk/by-partlabel/efi
                fstype: vfat

        - name: root
          block:
            - name: partition
              parted:
                name: root
                label: gpt
                device: /dev/sda
                number: 2
                state: present
                part_start: 512MiB

            - name: luks
              block:
                - name: luks container
                  luks_device:
                    device: /dev/disk/by-partlabel/root
                    name: root
                    state: opened
                    passphrase: test123

            - name: filesystem
              filesystem:
                dev: /dev/mapper/root
                fstype: btrfs

            - name: btrfs
              vars:
                subvolumes:
                  - id: "@"
                    mount: "/"
                  - id: "@home"
                    mount: "/home"
                  - id: "@tmp"
                    mount: "/tmp"
                  - id: "@nix"
                    mount: "/nix"
                  - id: "@var_log"
                    mount: "/var/log"
                  - id: "@var_cache"
                    mount: "/var/cache"
                  - id: "@var_tmp"
                    mount: "/var/tmp"
                  - id: "@snapshots"
                    mount: "/.snapshots"

              block:
                - name: mount root partition for subvol creation
                  mount:
                    path: /mnt
                    src: /dev/mapper/root
                    fstype: btrfs
                    state: mounted
                    fstab: /tmp/fstab.tmp

                - name: define btrfs role variable
                  set_fact:
                    btrfs__subvolumes: |
                      {{
                      btrfs__subvolumes | default({})
                      | combine({'/mnt/' + item.id: {'state': 'present'}})
                      }}
                  with_items: "{{ subvolumes }}"

                - name: create btrfs subvolumes
                  import_role:
                    name: btrfs

                - name: unmount root partition
                  mount:
                    path: /mnt
                    src: /dev/mapper/root
                    fstype: btrfs
                    state: unmounted
                    fstab: /tmp/fstab.tmp

                - name: mount root partition with opts
                  mount:
                    path: "/mnt{{item.mount}}"
                    src: /dev/mapper/root
                    fstype: btrfs
                    state: mounted
                    fstab: /tmp/fstab.final.tmp
                    opts: "noatime,subvol={{item.id}},compress=zstd"
                  with_items: "{{ subvolumes }}"

        - name: mount boot partition
          mount:
            path: /mnt/boot
            src: /dev/disk/by-partlabel/efi
            fstype: vfat
            state: mounted
            fstab: /tmp/fstab.final.tmp
