- hosts: localhost
  name: bootstrap
  connection: local
  become: true

  collections:
    - debops.debops

  vars:
    btrfs__subvolumes:
      "/mnt/@":
         state: present
      "/mnt/@tmp":
         state: present
      "/mnt/@var":
         state: present
      "/mnt/@home":
         state: present


  tasks:
    - name: boot partition
      community.general.parted:
        name: efi
        label: gpt
        device: /dev/sda
        number: 1
        state: present
        flags: [boot]
        part_end: 512MiB


    - name: root partition
      parted:
        name: nix
        label: gpt
        device: /dev/sda
        number: 2
        state: present
        part_start: 512MiB

    - name: boot filesystem
      filesystem:
        dev: /dev/sda1
        fstype: vfat

    - name: nix filesystem
      filesystem:
        dev: /dev/sda2
        fstype: btrfs

    - name: mount root partition for btrfs subvol creation
      mount:
        path: "/mnt"
        src: "PARTLABEL=nix"
        fstype: btrfs
        state: mounted
        fstab: /tmp/tmp.fstab

    - name: Create btrfs subvolumes
      import_role:
        name: btrfs

    - name: unmount root partition
      mount:
        path: "/mnt"
        src: "PARTLABEL=nix"
        fstype: btrfs
        state: unmounted
        fstab: /tmp/tmp.fstab

    - name: mount root partition with opts
      mount:
        path: "/mnt"
        src: "PARTLABEL=nix"
        fstype: btrfs
        state: mounted
        fstab: /tmp/tmp.fstab
        opts: 'noatime,subvol=@'


    - name: mount boot partition
      mount:
        path: "/mnt/boot"
        src: "PARTLABEL=efi"
        fstype: vfat
        state: mounted
        fstab: /tmp/tmp.fstab
