Vagrant.configure("2") do |config|
  config.vm.define :nix do |nix|
    nix.vm.box = "nixbox"
    # nix.vm.synced_folder ".", "/vagrant", :mount_options => ["ro"]
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.loader = "/usr/share/edk2-ovmf/x64/OVMF.fd"
    libvirt.driver = 'kvm'
    libvirt.nvram = "/var/lib/libvirt/qemu/nvram/nixos-21.11_VARS.fd"
    libvirt.video_type = 'qxl'
    # libvirt.boot = "hd"
    libvirt.machine_type = 'pc-q35-7.0'
    libvirt.cpu_mode = 'host-passthrough'
  end
end
