# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "virtio_pci" "virtio_scsi" "floppy" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.initrd.luks.devices.root.device = "/dev/disk/by-partlabel/root";
  boot.supportedFilesystems = ["btrfs"];

  fileSystems = {
    "/" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@" "noatime" "compress=zstd"];
    };

    "/home" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@home" "noatime" "compress=zstd"];
    };

    "/tmp" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@tmp" "noatime" "compress=zstd"];
    };

    "/nix" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@nix" "noatime" "compress=zstd"];
    };

    "/var/log" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@var_log" "noatime" "compress=zstd"];
      neededForBoot = true;
    };

    "/var/cache" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@var_cache" "noatime" "compress=zstd"];
    };

    "/var/tmp" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@var_tmp" "noatime" "compress=zstd"];
    };

    "/.snapshots" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = ["subvol=@snapshots" "noatime" "compress=zstd"];
    };

    "/boot" = {
      device = "/dev/disk/by-partlabel/efi";
      fsType = "vfat";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
